name: 'azure-work-item'
description: 'Creates work item like User Stories or Bugs in Azure Devops'

inputs:
  action:
    description: 'The action that you want to trigger. Accepted values ["bug", "user-story"]'
    required: true
  organization:
    description: 'Azure Devops organization'
    required: true
  project: 
    description: 'The project in the Azure Devops organization'
    required: true
  azure-devops-token:
    description: 'Access token to call the Azure Devops'
    required: true
  workitem-title: 
    description: 'The title of the work item'
    required: true
  workitem-description:
    description: 'The description of the work item'
    required: true
  workitem-area:
    description: 'Which area in the board is belongs to'
    required: false
  repo-link:
    description: 'Github repo that launch the issue'
    required: false

outputs:
  result:
    description: 'The outcome of the action'

runs:
  using: node16
  main: dist/index.js

branding:
  color: 'blue'
  icon: 'archive'